### ISSUE TITLE
レヴュー用issue

### ISSUE THREAD

**Issue by koujiendo1123** [koujiendo1123/8th_SunGallery2#62]
## 各種情報
サービス名:
8th_SunGallary

サービスURL:
https://www.8th-sungallery.com/

githubURL:
https://github.com/koujiendo1123/8th_SunGallery2

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 絵画画像アップロード機能（admin ユーザー画面から）
- [ ] 検索機能
- [x] 画像ダウンロード、印刷機能
- [x] ログイン
- [x] ユーザー登録
- [ ] ユーザー一覧
- [ ] ユーザー詳細
- [x] 絵画登録
- [x] 絵画一覧
- [x] 絵画詳細
- [ ] 絵画ジャンル
- [ ] ログイン（管理画面機能）
- [ ] ユーザー登録（管理画面機能）
- [ ] ユーザー一覧（管理画面機能）
- [ ] ユーザー詳細（管理画面機能）
- [ ] 絵画登録（管理画面機能）
- [ ] 絵画一覧（管理画面機能）
- [ ] 絵画詳細（管理画面機能）

## READMEレビュー時から変更した機能
作成しなかったもの
１）管理画面機能の全て
２）検索機能
注意：卒業制作課題の1-4までは別のリポジトリで作成を実施していました。
しかしながら、そちらのリポジトリに誤って重要情報をアップロードしていたため、そちらを削除しました。
そのため、同じ情報も持ったリポジトリを新たに作成し直しています。

## サービスイメージがわかるようなスクリーンショット等
TOP画面

<img width="1440" alt="スクリーンショット 2024-05-25 19 09 27" src="https://github.com/koujiendo1123/8th_SunGallery2/assets/72920603/0038c9c7-f512-4c66-956c-f29e56b4b488">

絵画アップロード画面（仮管理ユーザーのみログイン可能）
<img width="1440" alt="スクリーンショット 2024-05-25 19 11 02" src="https://github.com/koujiendo1123/8th_SunGallery2/assets/72920603/49035069-a8ae-44d5-b80c-44ce0916eaa1">

作者作成画面（仮管理ユーザーのみログイン可能）
<img width="1440" alt="スクリーンショット 2024-05-25 19 15 52" src="https://github.com/koujiendo1123/8th_SunGallery2/assets/72920603/3a8b8ace-0394-40bc-b5e8-0efed0034ff4">

**Comment by koujiendo1123** [comment]
ご担当者様
無理を言ってしまい恐縮ですが、2024年6月1日が卒業日なので可能な限り早めにご確認いただけると助かります。
よろしくお願い申し上げます。

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
機能の確認ができました。

LGTMです。

**Comment by koujiendo1123** [comment]
ご確認ありがとうございます。
こちらクローズとさせていただきます。
